#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

/* RETORNO GENERAL */
#define ERROR 1
#define TODO_BIEN 0

#define LISTA_DUPLICADO 2
#define LISTA_LLENA 2

#define PILA_VACIA 0
#define PILA_LLENA 1

#endif